version: '2.1'

services:
  database:
    container_name: database
    hostname: database
    image: mysql:latest
    restart: always
    env_file:
      - ./db.env
    ports:
      - '3307:3306'
    expose:
      - '3307'
    healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 10s
      timeout: 20s
      retries: 30

  tomcat:
    image: tomcat:9.0.27-jdk13-openjdk-oracle
    volumes:
      - ./target/SimpleRestfulAppinServlets-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/application.war
    ports:
      - '8888:8080'
    env_file:
      - ./tomcat.env
    depends_on:
      database:
        condition: service_healthy